### ISSUE TITLE
Problem in compiling the VICINITY Gateway

### ISSUE THREAD

**Issue by iacopocarrerasthinkin** [vicinityh2020/vicinity-gateway-api#4]
We started by downloading and compiling the gateway. In doing this we received the following error:

[INFO]                                                                        
[INFO] ------------------------------------------------------------------------
[INFO] Building OpenGatewayAPI 1.1
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.739 s
[INFO] Finished at: 2019-01-02T16:36:14+01:00
[INFO] Final Memory: 12M/358M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project OpenGatewayAPI: Could not resolve dependencies for project eu.bavenir:OpenGatewayAPI:jar:1.1: Failure to find com.github.jsonld-java.jsonld-java:jsonld-java:bundle:0.11.1 in http://maven.restlet.com was cached in the local repository, resolution will not be reattempted until the update interval of maven-restlet has elapsed or updates are forced -> [Help 1]

It look like there is a dependancy missing. 
Can you help on this (or direct us to the person we can support to)?

**Comment by AndrejSeben** [comment]
Add missing dependency (com.github.jsonld-java.jsonld-java)
