### ISSUE TITLE
error when agent request a login

### ISSUE THREAD

**Issue by fleyer** [vicinityh2020/vicinity-gateway-api#8]
From the moment I pulled the repository, my gateway fails to reach the vicinity network.

There are multiple exception see the attached file.

[19-07-25T10_09_11.563-gateway.log](https://github.com/vicinityh2020/vicinity-gateway-api/files/3431930/19-07-25T10_09_11.563-gateway.log)

I followed the tutorial many times without success. When I try to http get the agent/configuration everything is empty. I don't if it's the same with the docker version but it's not working.

**Comment by fleyer** [comment]
Here are the logs when I try to use the login (localhost:8181/api/objects/login with basic authentification header)

[19-07-30T09_03_58.714-gateway.log](https://github.com/vicinityh2020/vicinity-gateway-api/files/3446875/19-07-30T09_03_58.714-gateway.log)

I have hided some personal information with **[[username]]**

**Comment by Joralmi** [comment]
Hello,
We have tested the latest binary of the gateway in MAC and several linux distributions with no errors.
The error in the logs looks like there is some library missing for reading XML and the configuration cannot be loaded, we were not able to replicate it. Additionally seems that the HTTP server is not loaded properly.
I would recommend to try the docker version of the gateway which should help you overcome any configuration issue that there might be.

**Comment by fleyer** [comment]
The docker version is working as expected.

For maven, cleaned everything pulled the repo, build and it's still not working ...
